name: Build uv cache (Reusable)

on:
  workflow_call:
    inputs:
      UV_VERSION:
        required: false
        type: string
        default: '0.12.7'
      PYTHON_VERSION:
        required: false
        type: string
        default: '3.13'

jobs:
  build-cache:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
        with:
          version: ${{ inputs.UV_VERSION }}
          python-version: ${{ inputs.PYTHON_VERSION }}
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: Install dependencies
        run: uv sync --locked
