name: Unit Test & Coverage (Reusable)

on:
  workflow_call:
    inputs:
      UV_VERSION:
        required: false
        type: string
        default: '0.12.7'

      PYTHON_VERSION:
        required: false
        type: string
        default: '3.13'

jobs:
  unit-test-coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: ${{ inputs.UV_VERSION }}
          python-version: ${{ inputs.PYTHON_VERSION }}
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: Install dependencies
        run: uv sync --locked

      - name: Run unit tests with coverage
        run: |
          uv run coverage run -m pytest
          uv run coverage report --show-missing
